"""
fill_book.py

Automatically fills a Word "book" document with tables and figures
generated by your scripts, based on placeholder markers.

HOW TO USE
----------
1. In your book.docx (edited normally in Word), add a marker as its own
   paragraph wherever a table or figure should appear, e.g.:

       {{TABLE_SALES_Q1}}
       {{FIGURE_REVENUE_TREND}}

2. Have your scripts save their outputs into a folder (e.g. "content/"),
   naming each file EXACTLY after its marker:

       content/TABLE_SALES_Q1.html   (or .csv)
       content/FIGURE_REVENUE_TREND.png  (or .jpg)

3. Run:

       python fill_book.py book.docx content/ book_filled.docx

   Every marker with a matching file gets replaced automatically.
   Everything else in the document -- all the person's writing --
   is left completely untouched. Markers without a matching file
   are left in place (so you can see what's still missing) and
   listed in the console output.

Supported inputs:
  - Tables:  .html (first <table> found) or .csv
  - Figures: .png, .jpg, .jpeg
"""

import sys
import copy
from pathlib import Path

import pandas as pd
from docx import Document
from docx.shared import Inches
from docx.oxml.ns import qn


def _read_table(path: Path) -> pd.DataFrame:
    if path.suffix.lower() == ".csv":
        return pd.read_csv(path)
    else:  # .html
        tables = pd.read_html(path)
        if not tables:
            raise ValueError(f"No <table> found in {path}")
        return tables[0]


def _insert_table_before(paragraph, df: pd.DataFrame):
    """Build a native Word table from a DataFrame and place it where
    the marker paragraph currently sits."""
    doc = paragraph.part.document
    table = doc.add_table(rows=1, cols=len(df.columns))
    table.style = "Light Grid Accent 1"

    hdr_cells = table.rows[0].cells
    for i, col_name in enumerate(df.columns):
        hdr_cells[i].text = str(col_name)
        for run in hdr_cells[i].paragraphs[0].runs:
            run.bold = True

    for _, row in df.iterrows():
        cells = table.add_row().cells
        for i, val in enumerate(row):
            cells[i].text = "" if pd.isna(val) else str(val)

    # docx-python always appends new tables to the end of the document body.
    # Move the table's XML element to sit directly before the marker
    # paragraph, then remove the marker paragraph.
    tbl_element = table._tbl
    tbl_element.getparent().remove(tbl_element)
    paragraph._p.addprevious(tbl_element)
    paragraph._p.getparent().remove(paragraph._p)


def _insert_image_before(paragraph, image_path: Path, width_inches=6.0):
    """Insert an image where the marker paragraph currently sits."""
    # Create a new empty paragraph right before the marker, put the image
    # in it, then delete the marker paragraph.
    new_p = copy.deepcopy(paragraph._p)
    # strip any existing runs/text from the copy so we start clean
    for child in list(new_p):
        if child.tag == qn("w:r") or child.tag == qn("w:hyperlink"):
            new_p.remove(child)
    paragraph._p.addprevious(new_p)

    from docx.text.paragraph import Paragraph
    img_paragraph = Paragraph(new_p, paragraph._parent)
    run = img_paragraph.add_run()
    run.add_picture(str(image_path), width=Inches(width_inches))

    paragraph._p.getparent().remove(paragraph._p)

def fill_book(book_path: str, content_dir: str, output_path: str):
    doc = Document(book_path)
    content_dir = Path(content_dir)

    # Map marker name -> file path, based on filename (without extension)
    available = {}
    for f in content_dir.iterdir():
        if f.is_file():
            available[f.stem] = f

    filled, missing = [], []

    # Iterate over a static list of paragraphs since we'll be
    # adding/removing elements as we go.
    for paragraph in list(doc.paragraphs):
        text = paragraph.text.strip()
        if not (text.startswith("{{") and text.endswith("}}")):
            continue
        marker = text[2:-2].strip()

        if marker not in available:
            missing.append(marker)
            continue

        file_path = available[marker]
        try:
            suffix = file_path.suffix.lower()
            if suffix in (".png", ".jpg", ".jpeg"):
                _insert_image_before(paragraph, file_path)
                filled.append(marker)
            elif suffix in (".csv", ".html"):
                df = _read_table(file_path)
                _insert_table_before(paragraph, df)
                filled.append(marker)
            else:
                print(f"  Skipping {marker}: unsupported file type {suffix}")
        except Exception as e:
            print(f"  Failed to fill {marker}: {e}")

    doc.save(output_path)

    print(f"Filled {len(filled)} marker(s): {filled}")
    if missing:
        print(f"No matching file for {len(missing)} marker(s): {missing}")
    print(f"Saved: {output_path}")


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: python fill_book.py <book.docx> <content_dir> <output.docx>")
        sys.exit(1)
    fill_book(sys.argv[1], sys.argv[2], sys.argv[3])
